backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
              label: Hero Section,
              name: hero,
              widget: object,
              fields: [
                {label: Background Image, name: background_image, widget: image},
                {label: Title, name: title, widget: string},
                {label: Subtitle, name: subtitle, widget: string},
                {label: Skills List, name: skills_list, widget: object, fields: [{label: Skills, name: skills, widget: list, fields:[{label: Skill, name: skill, widget: string}]}]}
              ]
            }
          - {
              label: MiddleState Section,
              name: middlestate,
              widget: object,
              fields: [
                {label: Logo, name: logo, widget: image},
                {label: Heading, name: mdst_heading, widget: string},
                {
                  label: Grizzlyfest Project,
                  name: grizzlyfest,
                  widget: object,
                  fields: [
                    {label: Name, name: name, widget: string},
                    {label: Technologies Used, name: tech_used, widget: string},
                    {label: Description, name: description, widget: text},
                    {label: Website Link, name: website_link, widget: string},
                    {label: Repo Link, name: repo_link, widget: string}
                  ]
                },
                {
                  label: Cellar Door Project,
                  name: cellar_door,
                  widget: object,
                  fields: [
                    {label: Name, name: name, widget: string},
                    {label: Technologies Used, name: tech_used, widget: string},
                    {label: Description, name: description, widget: text},
                    {label: Website Link, name: website_link, widget: string},
                    {label: Repo Link, name: repo_link, widget: string}
                  ]
                },
                {
                  label: DataHarvest Project,
                  name: dataharvest,
                  widget: object,
                  fields: [
                    {label: Name, name: name, widget: string},
                    {label: Technologies Used, name: tech_used, widget: string},
                    {label: Description, name: description, widget: text},
                    {label: Website Link, name: website_link, widget: string},
                    {label: Repo Link, name: repo_link, widget: string}
                  ]
                }
              ]
            }