backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
        - label: Hero Section
          name: hero
          widget: object
          fields:
          - {label: Background Image, name: background_image, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: text}
          - label: Skills List
            name: skills_list
            widget: object
            fields:
            - label: Skills
              name: skills
              widget: list
              fields:
              - label: Skill
                name: skill
                widget: string
        - label: Shopify Section
          name: shopify
          widget: object
          fields:
          - {label: Icon, name: icon, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - {label: Subsection 1 Title, name: subsection_1_title, widget: string}
          - {label: Step 1 Image, name: step_1_image, widget: image}
          - {label: Step 2 Image, name: step_2_image, widget: image}
          - {label: Step 3 Image, name: step_3_image, widget: image}
          - {label: Step 4 Image, name: step_4_image, widget: image}
          - {label: Step 5 Image, name: step_5_image, widget: image}
          - {label: Step 6 Image, name: step_6_image, widget: image}
          - {label: Step 7 Image, name: step_7_image, widget: image}
          - {label: Step 8 Image, name: step_8_image, widget: image}
          - {label: Project Image, name: project_image, widget: image}
          - {label: Gif Image, name: gif_image, widget: image}
        - label: MiddleState Section
          name: middlestate
          widget: object
          fields:
          - {label: Icon, name: icon, widget: image}
          - {label: Icon Link, name: icon_link, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: text}
          - label: MiddleState Projects
            name: mdst_projects
            widget: object
            fields:
            - label: MiddleState Projects List
              name: mdst_projects_list
              widget: list
              fields:
              - label: Project
                name: project
                widget: object
                fields:
                - {label: Image, name: image, widget: image}
                - {label: Title, name: title, widget: string}
                - {label: Business Type, name: business_type, widget: string}
                - {label: Tech Used, name: tech_used, widget: string}
                - {label: Description, name: description, widget: text}
                - {label: Website Link, name: website_link, widget: string}
                - {label: Repo Link, name: repo_link, widget: string}
        - label: Testimonials Section
          name: testimonials
          widget: object
          fields:
          - {
              label: Ryan,
              name: ryan,
              widget: object,
              fields: [
                {label: Image, name: image, widget: image},
                {label: Quote, name: quote, widget: text},
                {label: Name, name: name, widget: string},
                {label: Title, name: title, widget: string}
              ]
            }
            